### ISSUE TITLE
Add License File

### ISSUE THREAD

**Issue by paretech** [jeremyherbert/mcp2210-python#11]
I noted that setup.py indicates MIT license but the project does not contain a LICENSE file. It would be a stronger signal and thus lower risk to incorporate this project by integrators if a LICENSE file were included that matches that indicated in setup.py. 

I would normally submit a PR but since this issue involves licensing, I would recommend that the authors or existing maintainers incorporate. Can you please add the MIT License file to this project?

**Comment by jeremyherbert** [comment]
Should be fixed now.
