### ISSUE TITLE
logs from the module mess up the root logger

### ISSUE THREAD

**Issue by ashokbruno** [jeremyherbert/mcp2210-python#12]
A better way to log messages would be log in a specific log for more control. This would allow the log to be disabled by upstream code using this module. For instance, this change would be modify line15 of mcp2210.py to:

logger = logging.getLogger(__name__)

**Comment by jeremyherbert** [comment]
Thank you for this. I have just pushed 1.0.7 to pypi with your fix included.

**Comment by ashokbruno** [comment]
Thanks!
