### ISSUE TITLE
Requirements for hid package

### ISSUE THREAD

**Issue by hollylmaness** [jeremyherbert/mcp2210-python#14]
Pip successfully installed this package following your documentation, but I was only able to successfully run it by replacing the following two lines:

https://github.com/jeremyherbert/mcp2210-python/blob/49d3cc1585bfbc0d55190086494535743038de6c/mcp2210/mcp2210.py#L461-L462

with:

self._hid = hid.Device(vid=vendor_id, pid=product_id)

Thank you so much for your work on this package!

**Comment by jeremyherbert** [comment]
Yeah, you do need to provide a serial number of your device so it can connect to the correct one. Unfortunately windows makes this relatively complicated to find for a given device. The adjustment you made is fine too.

**Comment by hollylmaness** [comment]
I'm using hid 1.0.6. on OS X, which shows the hid.Device method as upper case and doesn't take a serial number as input; there doesn't appear to be a hid.device method in the version I'm using, or a hid.open method.  Do you know what the source of the discrepancy is? Thanks again!

**Comment by jeremyherbert** [comment]
It doesn't use `hid`, it uses the package `hidapi`, do you have this installed? perhaps you have installed this with your python system environment that already had `hid` installed and as such have broken the install of `hidapi` ?

Try:
```
pip uninstall hid
pip install --force-reinstall hidapi
```

It might be worth trying to use this in a virtual environment if you need both packages, as it seems they are incompatible.

**Comment by hollylmaness** [comment]
Thanks so much for your help troubleshooting.  I did indeed have both hid and hidapi installed in my environment, so the "import hid" statement was using hid, not hidapi.  When I uninstalled hid, your package worked perfectly out of the box, just as you predicted.  Thanks again for your patience.

**Comment by jeremyherbert** [comment]
Great!
