### ISSUE TITLE
How to find the serial number?

### ISSUE THREAD

**Issue by Blitzbirnep** [jeremyherbert/mcp2210-python#6]
It seems to be a straight forward setting but I cant figure it out. How to find the serial number?

**Comment by jeremyherbert** [comment]
You can use lsusb -v on Linux, device manager on Windows, and System Report on mac.

**Comment by phoenixofhp** [comment]
Created pull request #8

**Comment by jeremyherbert** [comment]
@phoenixofhp thank you! merged and uploaded to pypi.
